#/bin/bash
# This file is auto generated by set-workspaces.sh. Please edit workspaces instead.

case $(hyprctl activeworkspace -j | jq -r '.id') in
    1) dc="steam";ac="" ;;
    2) dc="firefox";ac="" ;;
    3) dc="discord";ac="" ;;
    4) dc="spotify";ac="" ;;
    5) dc="code";ac="neovim" ;;
    6) dc="godot";ac="" ;;
    7) dc="blender";ac="" ;;
    8) dc="foot lazygit";ac="" ;;
    9) dc="foot";ac="" ;;
    10) dc="foot yazi";ac="nemo" ;;
    11) dc="foot btop";ac="" ;;
    12) dc="";ac="" ;;
    13) dc="";ac="" ;;
    14) dc="libreoffice";ac="" ;;
    15) dc="thunderbird";ac="" ;;
    *) dc="";ac="" ;;
esac

if [[ $1 == "dc" ]]; then
    eval "$dc" &
elif [[ $1 == "ac" ]]; then
    eval "$dc" &
fi
