#!/bin/bash

export_file=$HOME/.config/hypr/workspaces.conf
launch_script=$HOME/.config/hypr/launch.sh

echo "# This file is auto generated by set-workspaces.sh. Please edit workspaces instead." > $export_file
echo ""                                                                                   >> $export_file

echo "#/bin/bash"                                                                           > $launch_script
echo "# This file is auto generated by set-workspaces.sh. Please edit workspaces instead." >> $launch_script
echo ""                                                                                    >> $launch_script
echo "case \$(hyprctl activeworkspace -j | jq -r '.id') in"                                >> $launch_script

old_IFS="$IFS"
IFS=';'

i=1
while read line; do
    if [[ "$line" == "" ]] || [[ "$line" == \#* ]]; then
        continue
    fi

    line=($line)
    bu=$(echo "${line[0]}" | xargs)
    ws=$(echo "${line[1]}" | xargs)
    dc=$(echo "${line[2]}" | xargs)
    ac=$(echo "${line[3]}" | xargs)
    # bu - button
    # ws - workspace name
    # dc - default command
    # ac - alternate command
    
    echo "\$bu$i = $bu"                                    >> $export_file
    echo ""                                                >> $export_file
    echo "bind = \$mod, \$bu$i, workspace, $i"             >> $export_file
    echo "bind = \$mod SHIFT, \$bu$i, movetoworkspace, $i" >> $export_file
    echo "workspace = $i, defaultName:$ws"                        >> $export_file
    echo ""                                                >> $export_file
    echo ""                                                >> $export_file

    echo "    $i) dc=\"$dc\";ac=\"$ac\" ;;" >> $launch_script

    i=$(( $i + 1 ))
done < $HOME/.config/hypr/workspaces

IFS="$old_IFS"


echo "    *) dc=\"\";ac=\"\" ;;"      >> $launch_script
echo "esac"                           >> $launch_script
echo ""                               >> $launch_script
echo "if [[ \$1 == \"dc\" ]]; then"   >> $launch_script
echo "    eval \"\$dc\" &"            >> $launch_script
echo "elif [[ \$1 == \"ac\" ]]; then" >> $launch_script
echo "    eval \"\$dc\" &"            >> $launch_script
echo "fi"                             >> $launch_script
