$CONFIG = $HOME/.config/hypr/


exec-once = swaybg -o "*" -i $HOME/Pictures/Wallpapers/.png


decoration {
    rounding = 9
    blur {
	enabled = yes
	size = 2
	passes = 4
	noise = 0.0175
    }
}


# Start Waybar
exec-once = waybar

# Start Sway Notification Center
exec-once = swaync



$alt = MOD1
$mod = MOD4

# Reload Hyprland
bind = $mod SHIFT, C, exec, hyprctl reload


# Move focus to another window:
bind = $mod, left, movefocus, l
bind = $mod, down, movefocus, d
bind = $mod, up, movefocus, u
bind = $mod, right, movefocus, r

# Move the window:
bind = $mod SHIFT, left, movewindow, l
bind = $mod SHIFT, down, movewindow, d
bind = $mod SHIFT, up, movewindow, u
bind = $mod SHIFT, right, movewindow, r

# Resizing containers:
bind = $mod, R, resizewindow, # Enter resize mode
bind = $mod CTRL, left, resizeactive, -10 0
bind = $mod CTRL, down, resizeactive, 0 10
bind = $mod CTRL, up, resizeactive, 0 -10
bind = $mod CTRL, right, resizeactive, 10 0


# Execute a script to set workspace names
exec-always = $HOME/.config/hypr/set-workspaces.sh

# Include a separate file for workspace bindings
source = $HOME/.config/hypr/workspaces.conf


# Make the current focus fullscreen
bind = $mod, F, fullscreen, 0

# Move focus to the parent container
bind = $mod, A, focusparent,

# Kill focused window:
bind = $mod SHIFT, Q, killactive,


# Audio
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 2%+; pkill -RTMIN+8 waybar
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-; pkill -RTMIN+8 waybar
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle; pkill -RTMIN+8 waybar

# Audio Player
bind = , XF86AudioPrev, exec, playerctl previous
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next

# Brightness
bind = , XF86MonBrightnessDown, exec, light -U 5
bind = , XF86MonBrightnessUp, exec, light -A 5



# Open a terminal emulator:
bind = $mod $alt, T, exec, foot

# Open the application launcher:
bind = $mod, space, exec, wofi --show drun -i

# Default application for the current workspace
bind = $mod $alt, space, exec, $CONFIG/launch.sh dc
bind = $mod $alt SHIFT, space, exec, $CONFIG/launch.sh ac

# Take screenshot
bind = CTRL $alt, Tab, exec, $CONFIG/screenshot.sh

# Open notification pane:
bind = $mod, N, exec, swaync-client -t -sw



monitor=HDMI-A-1,2560x1440@144Hz,auto,1
