# -*- conf -*-

shell=/bin/fish

font=hack nerd font:size=12

[desktop-notifications]
command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}

[scrollback]
lines=100000

[key-bindings]
clipboard-copy=Control+c XF86Copy
clipboard-paste=Control+v XF86Paste

[colors]
alpha=0.6